# Macro file for the visualization setting in the initialization phase
# of the B1 example when running in interactive mode
#

# Use these open statements to open selected visualization
#
# Use this open statement to create an OpenGL view:
/vis/open OGL 600x600-0+0
#
# Use this open statement to create an OpenInventor view:
#/vis/open OI
#
# Use this open statement to create a .prim file suitable for
# viewing in DAWN:
#/vis/open DAWNFILE
#
# Use this open statement to create a .heprep file suitable for
# viewing in HepRApp:
#/vis/open HepRepFile
#
# Use this open statement to create a .wrl file suitable for
# viewing in a VRML viewer:
#/vis/open VRML2FILE
#
# Disable auto refresh and quieten vis messages whilst scene and
# trajectories are established:
/vis/viewer/set/autoRefresh false
#/vis/verbose errors
#
# Draw geometry:
/vis/drawVolume
#
# Specify view angle:
#/vis/viewer/set/viewpointVector -1 0 0
#/vis/viewer/set/lightsVector -1 0 0
#
# Specify style (surface, wireframe, auxiliary edges,...)
/vis/viewer/set/style wireframe
/vis/viewer/set/auxiliaryEdge true
/vis/viewer/set/lineSegmentsPerCircle 100
#
# Draw smooth trajectories at end of event, showing trajectory points
# as markers 2 pixels wide:
/vis/scene/add/trajectories rich
#/vis/modeling/trajectories/create/drawByCharge
#/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts false
#/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2
# (if too many tracks cause core dump => /tracking/storeTrajectory 0)
#
# Draw hits at end of event:
#/vis/scene/add/hits
#
# To draw only gammas:
# /vis/filtering/trajectories/create/particleFilter
# /vis/filtering/trajectories/particleFilter-0/add e+

#
# To invert the above, drawing all particles except gammas,
#/vis/filtering/trajectories/create/particleFilter
#/vis/filtering/trajectories/particleFilter-0/add e+
#/vis/filtering/trajectories/particleFilter-0/add e-
#/vis/filtering/trajectories/particleFilter-0/add mu+
#/vis/filtering/trajectories/particleFilter-0/add mu-
#/vis/filtering/trajectories/particleFilter-0/add gamma

# /vis/modeling/trajectories/create/drawByParticleID
# /vis/modeling/trajectories/drawByParticleID-0/set gamma green
# /vis/modeling/trajectories/drawByParticleID-0/set e+ blue
# /vis/modeling/trajectories/drawByParticleID-0/set e- red

/vis/filtering/trajectories/create/encounteredVolumeFilter Vol
/vis/filtering/trajectories/Vol/add Mu1
/vis/filtering/trajectories/Vol/add Mu2

###### TO FILTER TRACKS ACCORDING TO ENERGY!!!
#
/vis/modeling/trajectories/create/drawByAttribute EnCut
/vis/modeling/trajectories/EnCut/setAttribute IKE

/vis/modeling/trajectories/EnCut/addInterval interval1 0.0 keV 1 MeV
/vis/modeling/trajectories/EnCut/addInterval interval2 1 MeV 5 MeV
/vis/modeling/trajectories/EnCut/addInterval interval3 5 MeV 10 MeV
/vis/modeling/trajectories/EnCut/addInterval interval4 10 MeV 100 MeV
/vis/modeling/trajectories/EnCut/addInterval interval5 100 MeV 1 GeV
/vis/modeling/trajectories/EnCut/addInterval interval6 1 GeV 50 GeV

/vis/modeling/trajectories/EnCut/interval1/setDrawLine  1
/vis/modeling/trajectories/EnCut/interval2/setDrawLine  1
/vis/modeling/trajectories/EnCut/interval3/setDrawLine  1
/vis/modeling/trajectories/EnCut/interval4/setDrawLine  1
/vis/modeling/trajectories/EnCut/interval5/setDrawLine  1
/vis/modeling/trajectories/EnCut/interval6/setDrawLine  1
/vis/modeling/trajectories/EnCut/interval1/setLineColour red
/vis/modeling/trajectories/EnCut/interval2/setLineColour green
/vis/modeling/trajectories/EnCut/interval3/setLineColour blue
/vis/modeling/trajectories/EnCut/interval4/setLineColour yellow
/vis/modeling/trajectories/EnCut/interval5/setLineColour magenta
/vis/modeling/trajectories/EnCut/interval6/setLineColour white

#/vis/modeling/trajectories/EnCut/setAttribute PDG
#/vis/modeling/trajectories/EnCut/addValue fotoni 22
#/vis/modeling/trajectories/EnCut/fotoni/setLineColour yellow

################################


###### TO FILTER TRACKS ACCORDING TO PROCESS!!!
# /vis/modeling/trajectories/create/drawByAttribute Proc
# /vis/modeling/trajectories/Proc/setAttribute CPN
#
# /vis/modeling/trajectories/Proc/addValue brem_key eBrem
# /vis/modeling/trajectories/Proc/addValue annihil_key annihil
# /vis/modeling/trajectories/Proc/addValue conv_key conv
#
# /vis/modeling/trajectories/Proc/brem_key/setLineColour red
# /vis/modeling/trajectories/Proc/annihil_key/setLineColour green
# /vis/modeling/trajectories/Proc/conv_key/setLineColour blue

################################


# keep the above two lines but also add:
#/vis/filtering/trajectories/particleFilter-0/invert true
#
# Many other options are available with /vis/modeling and /vis/filtering.
# For example, to select colour by particle ID:
#
# /vis/modeling/trajectories/create/drawByParticleID
# /vis/modeling/trajectories/drawByParticleID-0/set gamma green
# /vis/modeling/trajectories/drawByParticleID-0/set e+ blue
# /vis/modeling/trajectories/drawByParticleID-0/set e- red

#/vis/modeling/trajectories/drawByParticleID-0/default/setDrawStepPts true
# To select or override default colours (note: e+ is blue by default):
#/vis/modeling/trajectories/list
#/vis/modeling/trajectories/drawByParticleID-0/set e+ yellow
#
# To superimpose all of the events from a given run:
/vis/scene/endOfEventAction accumulate
#
# Decorations
# Name
#/vis/set/textColour green
#/vis/set/textLayout right
#/vis/scene/add/text2D 0.9 -.9 24 ! ! exampleB1
# or, if your system does not support right-adjustment
#/vis/scene/add/text2D 0 -.9 24 ! ! exampleB1
#/vis/set/textLayout    # Revert to normal (left adjusted) layout
#/vis/set/textColour    # Revert to default text colour (blue)
#
# Axes, scale, etc.
#/vis/scene/add/scale   # Simple scale line
#/vis/scene/add/scale 31.324 m z 0 1 0 manual 0 0 15.662 m

## // were platforms BEFORE TB
# /vis/scene/add/scale 5.6 m z 0 1 0 manual 0 0 2.8 m
# /vis/scene/add/scale 15 m z 0 1 0 manual 0 0 7.5 m
# /vis/scene/add/scale 17.4 m z 0 1 0 manual 0 0 8.7 m
# /vis/scene/add/scale 17.8 m z 0 1 0 manual 0 0 8.9 m
# /vis/scene/add/scale 21 m z 0 1 0 manual 0 0 10.5 m
# /vis/scene/add/scale 21.1 m z 0 1 0 manual 0 0 10.55 m
# /vis/scene/add/scale 24.3 m z 0 1 0 manual 0 0 12.15 m

/vis/scene/add/scale 1886.3 cm z 1 1 1 manual 0 0 943.15 cm
/vis/scene/add/scale 2009.3 cm z 1 1 1 manual 0 0 1004.65 cm
/vis/scene/add/scale 2140.3 cm z 1 1 1 manual 0 0 1070.15 cm

/vis/scene/add/scale 21.15 m z 0 0 1 manual 0 0 10.575 m
/vis/scene/add/scale 21.60 m z 0 0 1 manual 0 0 10.8 m
/vis/scene/add/scale 22.20 m z 0 0 1 manual 0 0 11.1 m
/vis/scene/add/scale 22.70 m z 0 0 1 manual 0 0 11.35 m
#/vis/scene/add/axes    # Simple axes: x=red, y=green, z=blue.
/vis/scene/add/eventID # Drawn at end of event
#/vis/scene/add/scale 38.34 cm x 1 0 0 manual 0.1917 0 22.2 m
#/vis/scene/add/scale 23.6565 m z 0 0 1 manual 0 0 11.82825 m #inizio camera pre TB
/vis/scene/add/scale 23.8365 m z 0 0 1 manual 0 0 11.91825 m #inizio camera during TB

#/vis/scene/add/scale 24.1065 m z 0 0 1 manual 0 0 12.05325 m #fine camera pre TB
/vis/scene/add/scale 24.2865 m z 0 0 1 manual 0 0 12.14325 m #fine camera during TB
/vis/scene/add/scale 20.39 m z 1 0 0 manual 0 0 10.195 m

#/vis/scene/add/scale 25 cm x 0 1 1 manual 0.125 0 20.8 m
#/vis/scene/add/scale 27.34 cm x 0 1 1 manual 0.125 0 21.8 m
/vis/scene/add/scale 24 cm x 0 1 1 manual 0.12 0 21.4 m

/vis/scene/add/scale 48 cm x 0 1 1 manual 0. 0 23.8365 m
/vis/scene/add/scale 56 cm x 1 0 1 manual 0. 0 23.8365 m
/vis/scene/add/scale 32 cm x 1 0 1 manual 0. 0 2212.3 cm
/vis/scene/add/scale 41.5 cm x 1 0 1 manual 0. 0 2301.2 cm
/vis/scene/add/scale 2212.3 cm z 1 0 1 manual 0. 0 1106.15 cm
/vis/scene/add/scale 2301.2 cm z 1 0 1 manual 0. 0 1150.6 cm
/vis/scene/add/scale 2325.65 cm z 1 0 1 manual 0. 0 1162.83 cm
/vis/scene/add/scale 2365.65 cm z 1 0 1 manual 0. 0 1182.83 cm
#/vis/scene/add/scale  6 m z 1 0 0 manual 0 0 19.20 m
#/vis/scene/add/date    # Date stamp
/vis/scene/add/logo2D  # Simple logo
#/vis/scene/add/logo    # 3D logo
#
# Frame
/vis/set/colour red
/vis/set/lineWidth 2
/vis/scene/add/frame   # Simple frame around the view
/vis/set/colour        # Revert to default colour (white)
/vis/set/lineWidth     # Revert to default line width (1.)
#
# Attach text to one edge of Shape1, with a small, fixed offset
#/vis/scene/add/text 0 6 -4 cm 18 4 4 Shape1
# Attach text to one corner of Shape2, with a small, fixed offset
#/vis/scene/add/text 6 7 10 cm 18 4 4 Shape2
#
# To get nice view
/vis/geometry/set/visibility World 0 false
/vis/geometry/set/visibility Envelope 0 false
#/vis/geometry/set/visibility CaloTable1 0 false
#/vis/geometry/set/visibility CaloTable2 0 false

#/vis/viewer/set/style surface
/vis/viewer/set/hiddenMarker true
/vis/geometry/set/colour BP1 0 0.5 0.5 0.5 1
/vis/geometry/set/colour BP2 0 0.5 0.5 0.5 1
/vis/geometry/set/colour Mag 0 1 0 0 1
/vis/geometry/set/colour T1 0 1 1 0 1
/vis/geometry/set/colour T2 0 1 1 0 1
/vis/geometry/set/colour C0 0 1 1 0 1
/vis/geometry/set/colour Target 0 0 1 0 1
/vis/geometry/set/colour C1 0 1 1 0 1
/vis/geometry/set/colour C2 0 1 1 0 1
/vis/geometry/set/colour C3 0 1 1 0 1
/vis/geometry/set/colour C4 0 1 1 0 1
/vis/geometry/set/colour C5 0 1 1 0 1
/vis/geometry/set/colour C6 0 1 1 0 1
/vis/geometry/set/colour C7 0 1 1 0 1
/vis/geometry/set/colour S1 0 0 0 1 1
/vis/geometry/set/colour S2 0 0 0 1 1
/vis/geometry/set/colour S3 0 0 0 1 1
/vis/geometry/set/colour Pb1a 0 0 1 1   1
/vis/geometry/set/colour Pb1b 0 0 1 1   1
/vis/geometry/set/colour Pb1c 0 0 1 1   1
/vis/geometry/set/colour Pb2a 0 0 1 1   1
/vis/geometry/set/colour Pb2b 0 0 1 1   1
/vis/geometry/set/colour Pb2c 0 0 1 1   1
/vis/geometry/set/colour Ce1 0 0.5 .5 .5 0.6
/vis/geometry/set/colour Ce1Alu 0 0.7 .7 .7 .3
/vis/geometry/set/colour Ce1Fe 0 0.2 .2 .2 1
/vis/geometry/set/colour Ce1SiO 0 1 1 1 1
/vis/geometry/set/colour Ce2 0 0.5 .5 .5 0.6
/vis/geometry/set/colour Ce2Alu 0 0.7 .7 .7 .3
/vis/geometry/set/colour Ce2Fe 0 0.2 .2 .2 1
/vis/geometry/set/colour Ce2SiO 0 1 1 1 1
/vis/geometry/set/colour Mu1 0 0 1 0 1
/vis/geometry/set/colour Mu2 0 0 1 0 1
/vis/geometry/set/colour Ce1W 0 1 0 0  1
/vis/geometry/set/colour Ce1SiO 0 0 1 0 1
/vis/geometry/set/colour Ce2W 0 1 0 0  1
/vis/geometry/set/colour Ce2SiO 0 0 1 0 1
/vis/geometry/set/colour Ce1SiOtilt 0 0 1 0 1



#/vis/geometry/set/colour [logic name] depth R G B opacity
#/vis/viewer/set/viewpointThetaPhi 120 150
#/vis/viewer/set/viewpointThetaPhi 90 0
#/vis/viewer/set/viewpointThetaPhi -90 270 deg
#
#/vis/viewer/set/upVector 1 0 0
#/vis/viewer/set/viewpointThetaPhi 90 90
/vis/viewer/set/viewpointThetaPhi -90 -90
#/vis/viewer/set/targetPoint 0.5 0. 22.8 m #to view calos
/vis/viewer/set/targetPoint 0. 0. 22.8 m #to view calos
#/vis/viewer/set/targetPoint 0 0 16.42 m #to view magnet (Z10)
#/vis/viewer/set/targetPoint 0 0 20 m #to vie from magnet on (Z<10)
/vis/viewer/zoomTo 10
/vis/viewer/zoomTo 5


# Re-establish auto refreshing and verbosity:
/vis/viewer/set/autoRefresh true
/vis/verbose warnings
#
# For file-based drivers, use this to create an empty detector view:
#/vis/viewer/flush
