# Macro file for the visualization setting in the initialization phase
# of the B1 example when running in interactive mode
#

# Use these open statements to open selected visualization
#
# Use this open statement to create an OpenGL view:
/vis/open OGL 600x600-0+0
#
# Use this open statement to create an OpenInventor view:
#/vis/open OI
#
# Use this open statement to create a .prim file suitable for
# viewing in DAWN:
#/vis/open DAWNFILE
#
# Use this open statement to create a .heprep file suitable for
# viewing in HepRApp:
#/vis/open HepRepFile
#
# Use this open statement to create a .wrl file suitable for
# viewing in a VRML viewer:
#/vis/open VRML2FILE
#
# Disable auto refresh and quieten vis messages whilst scene and
# trajectories are established:
/vis/viewer/set/autoRefresh false
#/vis/verbose errors
#
# Draw geometry:
/vis/drawVolume
#
# Specify view angle:
#/vis/viewer/set/viewpointVector -1 0 0
#/vis/viewer/set/lightsVector -1 0 0
#
# Specify style (surface, wireframe, auxiliary edges,...)
/vis/viewer/set/style wireframe
/vis/viewer/set/auxiliaryEdge true
/vis/viewer/set/lineSegmentsPerCircle 100
#
# Draw smooth trajectories at end of event, showing trajectory points
# as markers 2 pixels wide:
/vis/scene/add/trajectories rich
#/vis/modeling/trajectories/create/drawByCharge
#/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts false
#/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2
# (if too many tracks cause core dump => /tracking/storeTrajectory 0)
#
# Draw hits at end of event:
#/vis/scene/add/hits
#
# To draw only gammas:
# /vis/filtering/trajectories/create/particleFilter
# /vis/filtering/trajectories/particleFilter-0/add e+

#
# To invert the above, drawing all particles except gammas,
 /vis/filtering/trajectories/create/particleFilter
 /vis/filtering/trajectories/particleFilter-0/add e+
# /vis/filtering/trajectories/particleFilter-0/add e-
 /vis/filtering/trajectories/particleFilter-0/add mu+
 /vis/filtering/trajectories/particleFilter-0/add mu-
#/vis/filtering/trajectories/particleFilter-0/add gamma
 /vis/filtering/trajectories/particleFilter-0/active 1

/vis/filtering/trajectories/create/particleFilter noGamma
/vis/filtering/trajectories/noGamma/add gamma
#/vis/filtering/trajectories/noGamma/invert 1
/vis/filtering/trajectories/noGamma/active 0

# /vis/modeling/trajectories/create/drawByParticleID
# /vis/modeling/trajectories/drawByParticleID-0/set gamma green
# /vis/modeling/trajectories/drawByParticleID-0/set e+ blue
# /vis/modeling/trajectories/drawByParticleID-0/set e- red

/vis/filtering/trajectories/create/encounteredVolumeFilter Vol
/vis/filtering/trajectories/Vol/add Mu1
#/vis/filtering/trajectories/Vol/add Mu2
# #/vis/filtering/trajectories/Vol/add Pb1a
# /vis/filtering/trajectories/Vol/add Pb1b
# #/vis/filtering/trajectories/Vol/add Pb1c
# /vis/filtering/trajectories/Vol/add Ce1
#/vis/filtering/trajectories/Vol/add S4
 /vis/filtering/trajectories/Vol/active 0

###### TO FILTER TRACKS ACCORDING TO ENERGY!!!
#
/vis/modeling/trajectories/create/drawByAttribute EnCut
/vis/modeling/trajectories/EnCut/setAttribute IKE

/vis/modeling/trajectories/EnCut/addInterval interval1 0.0 keV 1 MeV
/vis/modeling/trajectories/EnCut/addInterval interval2 1 MeV 5 MeV
/vis/modeling/trajectories/EnCut/addInterval interval3 5 MeV 10 MeV
/vis/modeling/trajectories/EnCut/addInterval interval4 10 MeV 100 MeV
/vis/modeling/trajectories/EnCut/addInterval interval5 100 MeV 1 GeV
/vis/modeling/trajectories/EnCut/addInterval interval6 1 GeV 50 GeV

/vis/modeling/trajectories/EnCut/interval1/setDrawLine  0
/vis/modeling/trajectories/EnCut/interval2/setDrawLine  0
/vis/modeling/trajectories/EnCut/interval3/setDrawLine  0
/vis/modeling/trajectories/EnCut/interval4/setDrawLine  0
/vis/modeling/trajectories/EnCut/interval5/setDrawLine  1
/vis/modeling/trajectories/EnCut/interval6/setDrawLine  1
/vis/modeling/trajectories/EnCut/interval1/setLineColour red
/vis/modeling/trajectories/EnCut/interval2/setLineColour green
/vis/modeling/trajectories/EnCut/interval3/setLineColour blue
/vis/modeling/trajectories/EnCut/interval4/setLineColour yellow
/vis/modeling/trajectories/EnCut/interval5/setLineColour magenta
/vis/modeling/trajectories/EnCut/interval6/setLineColour white

#/vis/modeling/trajectories/EnCut/setAttribute PDG
#/vis/modeling/trajectories/EnCut/addValue fotoni 22
#/vis/modeling/trajectories/EnCut/fotoni/setLineColour yellow

################################


###### TO FILTER TRACKS ACCORDING TO PROCESS!!!
# /vis/modeling/trajectories/create/drawByAttribute Proc
# /vis/modeling/trajectories/Proc/setAttribute CPN
#
# /vis/modeling/trajectories/Proc/addValue brem_key eBrem
# /vis/modeling/trajectories/Proc/addValue annihil_key annihil
# /vis/modeling/trajectories/Proc/addValue conv_key conv
#
# /vis/modeling/trajectories/Proc/brem_key/setLineColour red
# /vis/modeling/trajectories/Proc/annihil_key/setLineColour green
# /vis/modeling/trajectories/Proc/conv_key/setLineColour blue

################################


# keep the above two lines but also add:
#/vis/filtering/trajectories/particleFilter-0/invert true
#
# Many other options are available with /vis/modeling and /vis/filtering.
# For example, to select colour by particle ID:
#
#/vis/modeling/trajectories/create/drawByParticleID
# /vis/modeling/trajectories/drawByParticleID-0/set gamma green
# /vis/modeling/trajectories/drawByParticleID-0/set e+ blue
# /vis/modeling/trajectories/drawByParticleID-0/set e- red

#/vis/modeling/trajectories/drawByParticleID-0/default/setDrawStepPts true
# To select or override default colours (note: e+ is blue by default):
#/vis/modeling/trajectories/list
#/vis/modeling/trajectories/drawByParticleID-0/set e+ yellow
#
# To superimpose all of the events from a given run:
/vis/scene/endOfEventAction accumulate
#/vis/drawOnlyToBeKeptEvents
#
# Decorations
# Name
#/vis/set/textColour green
#/vis/set/textLayout right
#/vis/scene/add/text2D 0.9 -.9 24 ! ! exampleB1
# or, if your system does not support right-adjustment
#/vis/scene/add/text2D 0 -.9 24 ! ! exampleB1
#/vis/set/textLayout    # Revert to normal (left adjusted) layout
#/vis/set/textColour    # Revert to default text colour (blue)
#
# Axes, scale, etc.
#/vis/scene/add/scale   # Simple scale line
#/vis/scene/add/scale 31.324 m z 0 1 0 manual 0 0 15.662 m

## // were platforms BEFORE TB
# /vis/scene/add/scale 5.6 m z 0 1 0 manual 0 0 2.8 m
# /vis/scene/add/scale 15 m z 0 1 0 manual 0 0 7.5 m
# /vis/scene/add/scale 17.4 m z 0 1 0 manual 0 0 8.7 m
# /vis/scene/add/scale 17.8 m z 0 1 0 manual 0 0 8.9 m
# /vis/scene/add/scale 21 m z 0 1 0 manual 0 0 10.5 m
# /vis/scene/add/scale 21.1 m z 0 1 0 manual 0 0 10.55 m
# /vis/scene/add/scale 24.3 m z 0 1 0 manual 0 0 12.15 m
/vis/scene/add/scale 26 m z 0 1 0 manual 0 0 13 m

/vis/scene/add/scale 82.78 cm z 0 0 1 manual 0 0 41.39 cm # T1
/vis/scene/add/scale 441.63 cm z 0 0 1 manual 0 0 220.815 cm # T2
/vis/scene/add/scale 457.9 cm z 0 0 1 manual 0 0 228.85 cm #Targ
/vis/scene/add/scale 549.93 cm z 0 0 1 manual 0 0 274.965 cm #C0
/vis/scene/add/scale 1492.93 cm z 0 0 1 manual 0 0 746.465 cm #C1

/vis/scene/add/scale 1873.93 cm z 0 0 1 manual 0 0 936.965 cm #C2-3
/vis/scene/add/scale 1995.43 cm z 0 0 1 manual 0 0 997.715 cm #C4-5
/vis/scene/add/scale 2125 cm z 0 0 1 manual 0 0 1062.5 cm #C6-7

# /vis/scene/add/scale 2158.5 cm z 0 0 1 manual 0. 0 1079.25 cm
# /vis/scene/add/scale 2212.3 cm z 0 0 1 manual 0. 0 1106.15 cm
# /vis/scene/add/scale 2301.2 cm z 0 0 1 manual 0. 0 1150.6 cm
# /vis/scene/add/scale 2327.5 cm z 0 0 1 manual 0. 0 1163.75 cm
# /vis/scene/add/scale 2373.6 cm z 0 0 1 manual 0. 0 1186.8 cm
# /vis/scene/add/scale 2461.4 cm z 0 0 1 manual 0. 0 1230.7 cm
# /vis/scene/add/scale 3595 cm z 0 0 1 manual 0. 0 1797.5 cm

#
# /vis/scene/add/scale 21.15 m z 0 0 1 manual 0 0 10.575 m
# /vis/scene/add/scale 21.60 m z 0 0 1 manual 0 0 10.8 m
# /vis/scene/add/scale 22.20 m z 0 0 1 manual 0 0 11.1 m
# /vis/scene/add/scale 22.70 m z 0 0 1 manual 0 0 11.35 m
#/vis/scene/add/axes    # Simple axes: x=red, y=green, z=blue.
/vis/scene/add/eventID # Drawn at end of event
#/vis/scene/add/scale 38.34 cm x 1 0 0 manual 0.1917 0 22.2 m
#/vis/scene/add/scale 23.6565 m z 0 0 1 manual 0 0 11.82825 m #inizio camera pre TB
# /vis/scene/add/scale 23.8365 m z 0 0 1 manual 0 0 11.91825 m #inizio camera during TB

#/vis/scene/add/scale 24.1065 m z 0 0 1 manual 0 0 12.05325 m #fine camera pre TB
# /vis/scene/add/scale 24.2865 m z 0 0 1 manual 0 0 12.14325 m #fine camera during TB
# /vis/scene/add/scale 20.39 m z 1 0 0 manual 0 0 10.195 m

#/vis/scene/add/scale 25 cm x 0 1 1 manual 0.125 0 20.8 m
#/vis/scene/add/scale 27.34 cm x 0 1 1 manual 0.125 0 21.8 m

/vis/scene/add/scale 11.5 cm x 1 0 1 manual 0.0575 0 18.7393 m #C2-3

/vis/scene/add/scale 18 cm x 1 0 1 manual 0.09 0 19.9543 m #C4-5

/vis/scene/add/scale 24 cm x 1 0 1 manual 0.12 0 21.25 m #C6-7
/vis/scene/add/scale 18 cm x 1 0 1 manual -0.09 0 21.25 m #C7

/vis/scene/add/scale 48.23 cm x 1 0 1 manual 24.115 0 2169.33 cm # PbGlass1Startext 44_LUJ
/vis/scene/add/scale 45.63 cm x 1 0 1 manual -22.815 0 2163.4 cm # PbGlass2Startext 44_RUS
/vis/scene/add/scale 19.37 cm x 1 0 1 manual 9.685 0 2171.96 cm # PbGlass1Startin 44_LUS
/vis/scene/add/scale 16.77 cm x 1 0 1 manual -8.385 0 2165.72 cm # PbGlass2Startin 44_RUJ
/vis/scene/add/scale 53.65 cm x 1 0 1 manual 26.825 0 2207.43 cm # PbGlass1Endext 44_LDJ
/vis/scene/add/scale 51.25 cm x 1 0 1 manual -25.625 0 2201.6 cm # PbGlass2Endext 44_RDS
/vis/scene/add/scale 20.36 cm x 1 0 1 manual 10.18 0 2210.48 cm # PbGlass1EndInt 44_LDS
/vis/scene/add/scale 18.09 cm x 1 0 1 manual -9.045 0 2204.51 cm # PbGlass2EndInt 44_RDJ

/vis/scene/add/scale 52.44 cm x 1 0 1 manual 26.22 0 2228.37 cm # Ce1Startext 51_UJ
/vis/scene/add/scale 48.45 cm x 1 0 1 manual -24.225 0 2227.89 cm # Ce2Startext 52_US
/vis/scene/add/scale 21.77 cm x 1 0 1 manual 10.885 0 2229.89 cm # Ce1Startin 51_US
/vis/scene/add/scale 17.67 cm x 1 0 1 manual -8.835 0 2229.17 cm # Ce2Startin 52_UJ
/vis/scene/add/scale 56.99 cm x 1 0 1 manual 28.495 0 2319.75 cm # Ce1Endext 51_DJ
/vis/scene/add/scale 52.26 cm x 1 0 1 manual -26.13 0 2319.16 cm # Ce2Endext 52_DS
/vis/scene/add/scale 26.4 cm x 1 0 1 manual 13.2 0 2321.25 cm # Ce1EndInt 51_DS
/vis/scene/add/scale 21.5 cm x 1 0 1 manual -10.75 0 2320.45 cm # Ce2EndInt 52_DJ


# /vis/scene/add/scale 18.5 cm x 1 0 1 manual 9.25 0 2209 cm # Ce1Start
# #/vis/scene/add/scale 21.6 cm x 1 0 1 manual -10.8 0 2209 cm # Ce2Start - BEFORE -1cm
# /vis/scene/add/scale 20.6 cm x 1 0 1 manual -10.3 0 2209 cm # Ce2Start
#
# /vis/scene/add/scale 23.2 cm x 1 0 1 manual 11.6 0 2298 cm # Ce1End
# #/vis/scene/add/scale 26.3 cm x 1 0 1 manual -13.15 0 2298 cm # Ce2End  - BEFORE -1cm
# /vis/scene/add/scale 25.3 cm x 1 0 1 manual -12.65 0 2298 cm # Ce2End

#/vis/scene/add/scale 25.89 cm x 1 0 1 manual 0. 0 2196.66 cm #between LeadGlasses 2b
#/vis/scene/add/scale 32 cm x 1 0 1 manual 0. 0 2212.3 cm #between Cerenkovs
/vis/scene/add/scale 8.71 cm x 1 0 1 manual 4.335 0 2348.66 cm #Shield 1
/vis/scene/add/scale 30.54 cm x 1 0 1 manual -15.27 0 2347.07 cm #Shield 2

# /vis/scene/add/scale 47 cm x 0 1 1 manual 0. 0 2375.2 cm
# /vis/scene/add/scale 51 cm x 0 1 1 manual -2 0 2462.6 cm

#/vis/scene/add/scale 52.2 cm x 0 1 1 manual -4 0 2394.6 cm #between Mu upstream
#/vis/scene/add/scale 60.2 cm x 0 1 1 manual -4 0 2480 cm #between Mu downstream
/vis/scene/add/scale 22.29 cm x 0 1 1 manual 11.145 0 2394.6 cm
/vis/scene/add/scale 29.33 cm x 0 1 1 manual -14.665 0 2394.6 cm

/vis/scene/add/scale 91.65 cm x 0 1 1 manual 45.825 0 2394.6 cm
/vis/scene/add/scale 98.69 cm x 0 1 1 manual -49.345 0 2394.6 cm

/vis/scene/add/scale 25.04 cm x 0 1 1 manual 12.52 0 2480 cm
/vis/scene/add/scale 34.99 cm x 0 1 1 manual -17.495 0 2480 cm

/vis/scene/add/scale 94.38 cm x 0 1 1 manual 47.19 0 2480 cm
/vis/scene/add/scale 104.23 cm x 0 1 1 manual -52.115 0 2480 cm
/vis/scene/add/scale 4.8 cm x 1 1 1 manual 104.23 0 2480 cm
#/vis/scene/add/scale 56 cm x 1 0 1 manual 0. 0 23.8365 m
#/vis/scene/add/scale 41.5 cm x 1 0 1 manual 0. 0 2301.2 cm


#/vis/scene/add/scale  6 m z 1 0 0 manual 0 0 19.20 m
#/vis/scene/add/date    # Date stamp
/vis/scene/add/logo2D  # Simple logo
#/vis/scene/add/logo    # 3D logo
#
# Frame
/vis/set/colour red
/vis/set/lineWidth 2
/vis/scene/add/frame   # Simple frame around the view
/vis/set/colour        # Revert to default colour (white)
/vis/set/lineWidth     # Revert to default line width (1.)
#
# Attach text to one edge of Shape1, with a small, fixed offset
#/vis/scene/add/text 0 6 -4 cm 18 4 4 Shape1
# Attach text to one corner of Shape2, with a small, fixed offset
#/vis/scene/add/text 6 7 10 cm 18 4 4 Shape2
#
# To get nice view
/vis/geometry/set/visibility World 0 false
/vis/geometry/set/visibility Envelope 0 false
/vis/geometry/set/visibility CaloTable1 0 false
/vis/geometry/set/visibility CaloTable2 0 false
/vis/geometry/set/visibility Dummy1 0 true
/vis/geometry/set/visibility Dummy2 0 false

#/vis/viewer/set/style surface
/vis/viewer/set/hiddenMarker true
/vis/geometry/set/colour BP1 0 0.5 0.5 0.5 1
/vis/geometry/set/colour BP2 0 0.5 0.5 0.5 1
/vis/geometry/set/colour Mag 0 1 0 0 1
/vis/geometry/set/colour T1 0 1 1 0 1
/vis/geometry/set/colour T2 0 1 1 0 1
/vis/geometry/set/colour C0 0 1 1 0 1
/vis/geometry/set/colour Target 0 0 1 0 1
/vis/geometry/set/colour C1 0 1 1 0 1
/vis/geometry/set/colour C2 0 1 1 0 1
/vis/geometry/set/colour C3 0 1 1 0 1
/vis/geometry/set/colour C4 0 1 1 0 1
/vis/geometry/set/colour C5 0 1 1 0 1
/vis/geometry/set/colour C6 0 1 1 0 1
/vis/geometry/set/colour C7 0 1 1 0 1
/vis/geometry/set/colour S1 0 0 0 1 1
/vis/geometry/set/colour S2 0 0 0 1 1
/vis/geometry/set/colour S3 0 0 0 1 1
/vis/geometry/set/colour S4 0 0 0 1 1
/vis/geometry/set/colour S5 0 0 0 1 1
/vis/geometry/set/colour Pb1a 0 0 1 1   1
/vis/geometry/set/colour Pb1b 0 0 1 1   1
/vis/geometry/set/colour Pb1c 0 0 1 1   1
/vis/geometry/set/colour Pb2a 0 0 1 1   1
/vis/geometry/set/colour Pb2b 0 0 1 1   1
/vis/geometry/set/colour Pb2c 0 0 1 1   1
# /vis/geometry/set/colour Ce1 0 0.5 .5 .5 0.6
# /vis/geometry/set/colour Ce1Alu 0 0.7 .7 .7 .3
# /vis/geometry/set/colour Ce1Fe 0 0.2 .2 .2 1
# /vis/geometry/set/colour Ce1SiO 0 1 1 1 1
# /vis/geometry/set/colour Ce2 0 0.5 .5 .5 0.6
# /vis/geometry/set/colour Ce2Alu 0 0.7 .7 .7 .3
# /vis/geometry/set/colour Ce2Fe 0 0.2 .2 .2 1
# /vis/geometry/set/colour Ce2SiO 0 1 1 1 1
/vis/geometry/set/colour Mu1 0 0 1 0 1
/vis/geometry/set/colour Mu2 0 0 1 0 1
# /vis/geometry/set/colour CeVW 0 1 0 0  1
# /vis/geometry/set/colour CeVSiO 0 0 1 0 1
# /vis/geometry/set/colour CeVW 0 1 0 0  1
# /vis/geometry/set/colour CeVSiO 0 0 1 0 1
# /vis/geometry/set/colour CeVSiOtilt 0 0 1 0 1
# /vis/geometry/set/colour CeHW 0 1 0 0  1
# /vis/geometry/set/colour CeHSiO 0 0 1 0 1
# /vis/geometry/set/colour CeHW 0 1 0 0  1
# /vis/geometry/set/colour CeHSiOtilt 0 0 1 0 1
/vis/geometry/set/colour PbG 0 0 1 1   1
/vis/geometry/set/colour PbG2 0 1 1 1   1
/vis/geometry/set/colour PbG3 0 1 1 1   1
/vis/geometry/set/colour CeHSiO 0 0 1 0 1
/vis/geometry/set/colour CeVSiO 0 0 1 0 1
/vis/geometry/set/colour CeHW 0 1 0 0  1
/vis/geometry/set/colour CeVW 0 1 0 0  1
/vis/geometry/set/colour CeVSiOtilt 0 0 1 0 1
/vis/geometry/set/colour CeH 0 0.5 .5 .5 0.6
/vis/geometry/set/colour CeV 0 0.5 .5 .5 0.6
/vis/geometry/set/colour CeVAlu 0 0.7 .7 .7 .3
/vis/geometry/set/colour CeHAlu 0 0.7 .7 .7 .3
/vis/geometry/set/colour Shield 0 0.7 .7 .7 1
#/vis/geometry/set/colour [logic name] depth R G B opacity
#/vis/viewer/set/viewpointThetaPhi 120 150
#/vis/viewer/set/viewpointThetaPhi 90 0
#/vis/viewer/set/viewpointThetaPhi -90 270 deg
#
#/vis/viewer/set/upVector 1 0 0
#/vis/viewer/set/viewpointThetaPhi 90 90
/vis/viewer/set/viewpointThetaPhi -90 -90
#/vis/viewer/set/viewpointThetaPhi -90 0
#/vis/viewer/set/viewpointThetaPhi 180 90
#/vis/viewer/set/targetPoint 0.5 0. 22.8 m #to view calos
/vis/viewer/set/targetPoint 0. 0. 22.8 m #to view calos
#/vis/viewer/set/targetPoint 0 0 16.42 m #to view magnet (Z10)
#/vis/viewer/set/targetPoint 0. 0. 36.8 m #to view calos
#/vis/viewer/set/targetPoint 0. 0. 35 m #to view calos
#/vis/viewer/set/targetPoint 0 0 20 m #to vie from magnet on (Z<10)
/vis/viewer/zoomTo 10
#/vis/viewer/zoomTo 5
#/vis/viewer/set/background white

# Re-establish auto refreshing and verbosity:
/vis/viewer/set/autoRefresh true
/vis/verbose warnings
#
# For file-based drivers, use this to create an empty detector view:
#/vis/viewer/flush
